# Generated by Django 5.2.3 on 2025-07-07 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('OtherName', models.CharField(blank=True, max_length=50, null=True)),
                ('MatricNumber', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Level', models.CharField(blank=True, max_length=20, null=True)),
                ('Department', models.CharField(max_length=100)),
                ('Faculty', models.CharField(max_length=100)),
                ('User_Role', models.CharField(choices=[('Student', 'Student'), ('Lecturer', 'Lecturer')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FingerprintMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_id', models.IntegerField(unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apis.user')),
            ],
        ),
    ]
