# Generated by Django 5.2.3 on 2025-07-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fingerprintmapping',
            name='user',
        ),
    ]
